version: 2.1
orbs:
  scanner: boostsecurityio/scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
filters: &filters
  tags:
    only: /.*/
jobs:
  integration-test-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - boostsec/scan:
          api_token_var: BOOST_API_TOKEN
workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters: *filters
      - integration-test-1:
          context: boostsecurity-dev
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: boostsecurityio/scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
